# Generated by Django 5.2.18 on 2026-10-07 19:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoParceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('descricao', models.TextField(help_text='Ex.: curso de manejo sanitário, liberação de crédito do Agroamigo.', verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name': 'Ação de parceiro',
                'verbose_name_plural': 'Ações de parceiros',
                'db_table': 'acoes_parceiros',
                'ordering': ['-data_acao', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColetaProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da coleta')),
                ('total_produtores', models.PositiveIntegerField(default=0, verbose_name='Total de produtores')),
                ('qtd_caprinos', models.PositiveIntegerField(default=0, verbose_name='Caprinos (cabeças)')),
                ('qtd_ovinos', models.PositiveIntegerField(default=0, verbose_name='Ovinos (cabeças)')),
                ('criacao_extensiva', models.PositiveIntegerField(default=0, verbose_name='Criação extensiva')),
                ('criacao_semi_extensiva', models.PositiveIntegerField(default=0, verbose_name='Criação semi-extensiva')),
                ('criacao_intensiva', models.PositiveIntegerField(default=0, verbose_name='Criação intensiva')),
                ('escrituracao_sim', models.PositiveIntegerField(default=0, verbose_name='Fazem escrituração')),
                ('escrituracao_nao', models.PositiveIntegerField(default=0, verbose_name='Não fazem escrituração')),
                ('observacoes', models.TextField(blank=True, help_text='Nota técnica de campo, exibida no painel lateral do mapa.', null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Coleta de produção',
                'verbose_name_plural': 'Coletas de produção',
                'db_table': 'coletas_producao',
                'ordering': ['-data_coleta', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('municipio', models.CharField(blank=True, help_text='Habilita o filtro de município no mapa. Escreva sempre do mesmo jeito.', max_length=100, null=True, verbose_name='Município')),
                ('informacoes_adicionais', models.TextField(blank=True, help_text='Texto exibido no painel lateral do mapa, em “Informações de Cadastro”.', null=True, verbose_name='Informações adicionais')),
                ('latitude', models.FloatField(help_text='Graus decimais, negativo no hemisfério sul. Ex.: -9.3845', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Graus decimais, negativo a oeste de Greenwich. Ex.: -40.2534', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'comunidades',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalParceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Agência Petrolina, Escritório Regional de Juazeiro', max_length=150, verbose_name='Nome do local')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('latitude', models.FloatField(help_text='Graus decimais, negativo no hemisfério sul. Ex.: -9.3845', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Graus decimais, negativo a oeste de Greenwich. Ex.: -40.2534', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Localização de parceiro',
                'verbose_name_plural': 'Localizações de parceiros',
                'db_table': 'locais_parceiros',
                'ordering': ['parceiro__nome', 'nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, help_text='Rótulo curto do pino no mapa. Ex.: BNB', max_length=30, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'db_table': 'parceiros',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
    ]
